### ISSUE TITLE
Binaries for new releases

### ISSUE THREAD

**Issue by sj26** [barnybug/s3#12]
This is amazing! Could you please add binaries for the newest releases?

**Comment by barnybug** [comment]
Thanks! The binaries are up to date with the latest release.

**Comment by sj26** [comment]
🙇‍♂️

**Comment by sj26** [comment]
Sorry, it looks like 1.1.11 doesn't have binaries:

https://github.com/barnybug/s3/releases/tag/1.1.11

It doesn't look like there have been any application feature changes, but compiling with go 1.10 would come with a bunch of stuff which would be nice.
